/**
 * Códigos de permiso que usa el backend ParqueRM.
 * Estos strings vienen dentro del JWT en el campo `permissions[]`.
 * Solo se usan en frontend para mostrar/ocultar UI — la seguridad real está en el backend.
 */
export const PERMISSIONS = {
  // Usuarios
  USERS_READ: 'USERS_READ',
  USERS_MANAGE: 'USERS_MANAGE',

  // Roles
  ROLES_READ: 'ROLES_READ',
  ROLES_MANAGE: 'ROLES_MANAGE',

  // Visitantes
  VISITANTES_READ: 'VISITANTES_READ',
  VISITANTES_CREATE: 'VISITANTES_CREATE',
  VISITANTES_UPDATE: 'VISITANTES_UPDATE',
  VISITANTES_CHECKOUT: 'VISITANTES_CHECKOUT',

  // Vehículos
  VEHICULOS_READ: 'VEHICULOS_READ',
  VEHICULOS_CREATE: 'VEHICULOS_CREATE',
  VEHICULOS_UPDATE: 'VEHICULOS_UPDATE',
  VEHICULOS_ENABLE_EXIT: 'VEHICULOS_ENABLE_EXIT',

  // Hospedaje
  HOSPEDAJE_READ: 'HOSPEDAJE_READ',
  HOSPEDAJE_CREATE: 'HOSPEDAJE_CREATE',
  HOSPEDAJE_UPDATE: 'HOSPEDAJE_UPDATE',

  // Recibos
  RECEIPTS_READ: 'RECEIPTS_READ',
  RECEIPTS_CREATE: 'RECEIPTS_CREATE',
  RECEIPTS_CANCEL: 'RECEIPTS_CANCEL',
  RECEIPTS_PRINT: 'RECEIPTS_PRINT',

  // Caja
  CAJA_READ: 'CAJA_READ',
  CAJA_CREATE_MOVEMENT: 'CAJA_CREATE_MOVEMENT',
  CAJA_CANCEL_MOVEMENT: 'CAJA_CANCEL_MOVEMENT',
  CAJA_CLOSE: 'CAJA_CLOSE',

  // Reportes
  REPORTES_READ: 'REPORTES_READ',
  REPORTES_EXPORT: 'REPORTES_EXPORT',

  // Configuración
  CONFIG_READ: 'CONFIG_READ',
  CONFIG_UPDATE: 'CONFIG_UPDATE',

  // Catálogos
  CATALOGS_READ: 'CATALOGS_READ',
  CATALOGS_MANAGE: 'CATALOGS_MANAGE',

  // Auditoría
  AUDIT_READ: 'AUDIT_READ',

  // Tarifas
  TARIFF_OVERRIDE: 'TARIFF_OVERRIDE',

  // Encuestas
  SURVEYS_CONFIG_READ: 'SURVEYS_CONFIG_READ',
  SURVEYS_CONFIG_MANAGE: 'SURVEYS_CONFIG_MANAGE',
  SURVEYS_REPORT_READ: 'SURVEYS_REPORT_READ',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
